version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    shm_size: 1g

  app:
    image: app
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - ${SERVE_PORT}:80
    environment:
      - DB_HOST=postgres
      - DB_PASS=${DB_PASS}
    depends_on:
      postgres:
        condition: service_healthy

